### PR TITLE
fix(network): prevent sending redundant commands

### LINKED ISSUE #228: Send only necessary commands to retrieve the request post data
**Stack trace**
An output of execution with `NODE_DEBUG=cypress-har-generator` in the environment:

```
CYPRESS-HAR-GENERATOR 45676: The plugin sends to the CDP: {"id":7,"method":"Network.getRequestPostData","params":{"requestId":"FD2C692DA16C42898656D6280EA620A0"}}
CYPRESS-HAR-GENERATOR 50148: The plugin receives from the CDP: {"id":7,"error":{"code":-32000,"message":"No post data available for the request"},"sessionId":"C40321408052EA86C1D0A271345D56CD"}
```

**Steps to reproduce**
1. Create a simple mock server as shown below:
```js
import express from 'express';
import bodyParser from 'body-parser';
import exphbs from 'express-handlebars';

const app = express();

// configure middleware
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

// configure view engine
app.engine('.hbs', exphbs({ extname: '.hbs' }));
app.set('view engine', '.hbs');

// serve the index page
app.get('/', (_: Request, res: Response) => res.render('./index.hbs'));

// define a route for handling POST requests
app.get('/api/echo', (req: Request, res: Response) => res.json(req.body));

// start the server
const port = 3000;
app.listen(port, () => {
  console.log(`Server started on http://localhost:${port}`);
});
```
The `index.hbs` file should look like this:

```hbs
<html>
  <body>
    <h1>Post Data</h1>
    <pre></pre>
  </body>
  <script>
    const postData = {
      document: document.body.innerHTML,
    };
    const pre = document.querySelector('pre')

    fetch('/api/echo', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(postData)
    })
      .then(response => response.json())
      .then(data => pre.innerText = JSON.stringify(data, null, 2))
      .catch(error => console.error(error));
  </script>
</html>

```
2. Open a page and start recording using the following code:

```ts
cy.recordHar({ content: false });

cy.visit('/');

cy.saveHar({ waitForIdle: true });
```

**Actual behavior**
Although the HAR is recorded and postData is present in the corresponding request, the plugin tries to retrieve the request post data for multiple other requests, as indicated by the logs. This results in redundant commands being sent.

### PR DESCRIPTION
**Pull request by derevnjuk**
closes #228

### CODE REVIEW

File: src/cdp/DefaultNetwork.ts [hunk 1]
```diff
@@ -59,6 +59,7 @@ export class DefaultNetwork implements Network {
       ]);
     } catch (e) {
       // ADHOC: handle any unforeseen issues while detaching from targets.
+      this.logger.debug(`Unforeseen error while detaching from targets: ${e}`);
```
Comment (Sija) [inline src/cdp/DefaultNetwork.ts:62]:
```suggestion
      this.logger.debug(`Unexpected error while detaching from targets: ${e}`);
```

Comment (derevnjuk) [reply src/cdp/DefaultNetwork.ts:62]: I don't think so, this error has no impact on the flow or results.
